---
name: 'GUAC Ingest'
description: 'Ingest files into GUAC'
branding:
  icon: "shield"
  color: "purple"
author: 'Kusari'
inputs:
  files:
    description: 'path to directory or specific file to ingest'
    required: true
  api-addr:
    description: 'endpoint for graphql api for GUAC'
    required: true
  token-url:
    description: 'url for auth token provider'
    required: true
  client-id:
    description: 'client id for auth token provider'
    required: true
  client-secret:
    description: 'client secret for auth token provider'
    required: false
    default: ''
outputs:
  console_out:
    description: 'raw console output from guacone command'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.files }}
    - ${{ inputs.client-id }}
    - ${{ inputs.client-secret }}
    - ${{ inputs.api-addr }}
    - ${{ inputs.token-url }}
